[package]
name = "cognition"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde_json = "1.0"
tokio = "1.26.0"