[package]
name = "simula_sdf"
version = "0.1.0"
edition = "2021"
authors = ["Duncan <bonsairobo@gmail.com>", "Alex Rozgo <alex.rozgo@gmail.com>"]

[dependencies]
bevy = "0.9"
static_assertions = "1.1"

[dev-dependencies]
