[package]
name = "simula_cad"
version = "0.1.0"
edition = "2021"
authors = ["Alex Rozgo <alex.rozgo@gmail.com>"]

[dependencies]
bevy = { version = "0.10" }

fj = "0.46"
fj-math = "0.46"
fj-operations = "0.46"
fj-interop = "0.46"

[dev-dependencies]
