[package]
name = "simula_camera"
version = "0.1.0"
edition = "2021"
authors = ["Alex Rozgo <alex.rozgo@gmail.com>"]

[dependencies]
bevy = { version = "0.10" }
simula_action = { path = "../../crates/simula_action" }

[lib]
path = "lib.rs"
