[package]
name = "simula_viz"
version = "0.1.0"
edition = "2021"
authors = ["Alex Rozgo <alex.rozgo@gmail.com>"]

[dependencies]
bevy = { version = "0.10" }
bytemuck = "1.13"
simula_core = { path = "../../crates/simula_core" }

[lib]
path = "src/lib.rs"