[package]
name = "simula_viz"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.6"}
mikktspace = "0.2.0"
simula_core = { path = "../../crates/simula_core" }

[lib]
path = "lib.rs"