[package]
name = "simula_mission"
version = "0.1.0"
edition = "2021"

[dependencies]
ta = "0.5"
bevy = { version = "0.8" }
serde = { version = "1.0", features = ["derive"] }
ron = "0.8"
hex = "0.4"
bevy_egui = "0.16.1"
bevy-inspector-egui = "0.13"

[dev-dependencies]
